name: Snapshot build

on:
  push:
    branches: [ 'master' ]

jobs:
  publish:
    if: |
      github.repository == 'javalin/javalin' &&
      !contains(github.event.head_commit.message, '[maven-release-plugin] prepare release')
    name: Publish snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Grant execute permission for mvnw
        run: chmod +x ./mvnw
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "reposilite-repository",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]
      - name: Publish with Maven
        run: ./mvnw -DRunningOnCi=true clean deploy --file pom.xml --batch-mode -P publish-snapshot
